[package]
name = "portal-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
portal = { path = "../portal" }

serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
