[book]
title = "Portal Book"
description = ""
authors = ["Portal Technologies Inc"]
language = "en"
src = "."

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"

additional-js = ["./tabs.js"]

edit-url-template = "https://github.com/PortalTechnologiesInc/lib/edit/master/docs/{path}"
site-url = "/docs/"

git-repository-url = "https://github.com/PortalTechnologiesInc/lib"


# [output.html.search]
# enable = true
# limit-results = 30
# teaser-word-count = 30
# use-boolean-and = true
# boost-title = 2
# boost-hierarchy = 1
# boost-paragraph = 1
# expand = true
